### ISSUE TITLE
chore: switch to pinning a major or minor version instead of a patch version

### ISSUE THREAD

**Issue by xynydev** [blue-build/template#12]
Once https://github.com/blue-build/github-action/pull/19 is released, we'll have the `@v1`, `@v1.1`, and `@v1.1.0` tags available.

I'm unsure whether to pin to the major (`v1`) version or the minor (`v1.1`) version. With major versions it would be very automatic for users, but they also wouldn't get notified of new features by Dependabot.

**Comment by fiftydinar** [comment]
> Once [blue-build/github-action#19](https://github.com/blue-build/github-action/pull/19) is released, we'll have the `@v1`, `@v1.1`, and `@v1.1.0` tags available.
> 
> I'm unsure whether to pin to the major (`v1`) version or the minor (`v1.1`) version. With major versions it would be very automatic for users, but they also wouldn't get notified of new features by Dependabot.

If minor versions fix some ground-breaking change, I think that we should release that as an exception.

**Comment by xynydev** [comment]
> If minor versions fix some ground-breaking change, I think that we should release that as an exception.

Patch versions (the third number) have fixes, minor versions have features. Although, if there are both fixes and features in line, it will turn into a minor version. Hmm. I'm not sure exceptions are possible here, though.

**Comment by xynydev** [comment]
[5d9cc76](https://github.com/blue-build/template/commit/5d9cc7654c4d9e5c96b1749d6948077cb9e4b6ba) closes this

_Was supposed to be a PR but I forgot to check out the branch. But oh well..._
