### ISSUE TITLE
[ recipe.yml ] Firefox removal: Build failure warning for missing RPMs in upstream image

### ISSUE THREAD

**Issue by cig0** [blue-build/template#16]
Hi all,

When configuring my recipes to remove Firefox RPMs from the upstream image (in favor of the Flatpak version), the pipeline fails because said packages are missing from the upstream image I switched to (`kinoite-main` -> `bazzite`).

The issue is triggered when `rpm-ostree uninstall firefox` is performed, which will throw an exit code 1, making the pipeline fail.

As previously discussed on Discord:
  - With @bayou-brogrammer: https://discord.com/channels/1198292321037455360/1200874814349508629/1212875808914415637
  - With @xynydev: https://discord.com/channels/1198292321037455360/1212997762614956052

A proposed solution is to leave a heads-up comment on the Firefox removal section in the recipe template, warning the user the pipeline will fail if Firefox RPMs are missing from the upstream image.

**Comment by xynydev** [comment]
It is also worth discussing whether the firefox removal should be kept in the default recipe. It is an opinionated choice that not everyone might want to make, after all. I agree with _doing_ it, certainly, but having it in the default recipe makes doing it _implicit_ for many users.

**Comment by cig0** [comment]
> It is also worth discussing whether the firefox removal should be kept in the default recipe. It is an opinionated choice that not everyone might want to make, after all. I agree with _doing_ it, certainly, but having it in the default recipe makes doing it _implicit_ for many users.

I understand that the idea is to eventually phase out Firefox's RPM-based installation in favor of Flatpak (for Universal Blue images), so maybe this discussion might also involve the rest of the team...

**Comment by xynydev** [comment]
> I understand that the idea is to eventually phase out Firefox's RPM-based installation in favor of Flatpak (for Universal Blue images)

This is something that wont happen with ublue unless Fedora does it first, though. Fedora should do it, but that's not up to me. 

I'm waiting for some other eyes on this issue, though.

**Comment by fiftydinar** [comment]
I would put those in # as an example, but not as a "rule", as it's now.

**Comment by xynydev** [comment]
Could just do that I guess, yeah

**Comment by gmpinder** [comment]
I agree with this direction.
