### ISSUE TITLE
Build Custom Image failed due to "no space left on device"

### ISSUE THREAD

**Issue by bigjazzsound** [blue-build/template#18]
I've been a user of https://github.com/blue-build/legacy-template for a while now and went to migrate to this template.

I copied my [recipe.yml](https://github.com/bigjazzsound/os/blob/main/config/recipe.yml) directly from my fork of the legacy-template, where it used to run without this issue, but now I'm getting this error.

Logs: https://github.com/bigjazzsound/os/actions/runs/8151428872/job/22279283500

**Comment by fiftydinar** [comment]
> I've been a user of https://github.com/blue-build/legacy-template for a while now and went to migrate to this template.
> 
> I copied my [recipe.yml](https://github.com/bigjazzsound/os/blob/main/config/recipe.yml) directly from my fork of the legacy-template, where it used to run without this issue, but now I'm getting this error.
> 
> Logs: https://github.com/bigjazzsound/os/actions/runs/8151428872/job/22279283500

You can try to add this into GitHub action build.yml as a preference, at the end of the file:
https://blue-build.org/reference/github-action/#maximize_build_space-optional

But I wonder why you get that error still, you're not on some heavy image like bluefin as a base, but Sway Atomic.
You added nice amount of packages, but not something that is big in size as far as I look.

**Comment by bigjazzsound** [comment]
> You can try to add this into GitHub action build.yml as a preference, at the end of the file: https://blue-build.org/reference/github-action/#maximize_build_space-optional

This fixed it for me. Thank you for the suggestion.
