### ISSUE TITLE
Error on rebasing to unsigned image

### ISSUE THREAD

**Issue by mathetes87** [blue-build/template#23]
Hi, I followed the guide to set up a new repository and everything seemed to go well. The unmodified images from the stock template are published in ghcr.io and I could verify that the public key matches the signature.

```sh
❯ cosign verify --key cosign.pub ghcr.io/mathetes87/ublue-mathetes-kde:latest

Verification for ghcr.io/mathetes87/ublue-mathetes-kde:latest --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The signatures were verified against the specified public key
```

I installed Bluefin in a VirtualBox image and tried to rebase but got this error

``` sh
❯ rpm-ostree rebase ostree-unverified-registry:ghcr.io/mathetes87/ublue-mathetes-kde:latest
Pulling manifest: ostree-unverified-registry:ghcr.io/mathetes87/ublue-mathetes-kde:latest
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: unable to retrieve auth token: invalid username/password: unauthorized
```

I rebased Bluefin successfully to the latest version and checked that podman reports successful login to ghcr.io.
This error seems similar to [this issue](https://github.com/blue-build/template/issues/13) but my (attached)
 `/etc/containers/policy.json` looks fine? This is a new installation and also new repository.
[policy.json](https://github.com/blue-build/template/files/14606454/policy.json)

Thanks for any help!

**Comment by xynydev** [comment]
It seems that your custom image is set as private on GitHub's side. This is a know issue caused by a change on GitHub's side, and our documentation is currently lacking information on this.

https://github.com/blue-build/website/issues/40 is the tracking issue on our side. I can hopefully change the documentation this weekend.
