### ISSUE TITLE
Gh OIDC keyless

### ISSUE THREAD

**Issue by mecattaf** [blue-build/template#26]
Hi all, is github OIDC planned for this project? Happy to help if you can give me pointers.

To reference from the bluefin repo: https://github.com/ublue-os/bluefin/pull/907

**Comment by xynydev** [comment]
Yup, it is. That PR is actually from @bayou-brogrammer who is part of the org / team. Unfortunately there are some issues with rpm-ostree / upstream verification support. This is the (badly named) tracking issue: https://github.com/blue-build/cli/issues/84

**Comment by mecattaf** [comment]
Thanks @xynydev closing this since the team is on it 😀
