### ISSUE TITLE
Update build action to use commit hashes for versioning of other used actions

### ISSUE THREAD

**Issue by fiftydinar** [blue-build/template#41]
Currently, we use normal versioning, which is more intuitive & looks clearer in logs, but it's also less secure than using direct commit hashes for specifying the version.

`blue-build/github-action@v1.7.0`

Specifying direct commit hashes as a version has the advantage that it makes it impossible for the bad actor to override the behavior of the same-versioned action.

`blue-build/github-action@33ee8cc4011b0d47666ea7026d08bb5b941ac90c # v1.7.0`

Codacy also recommends to do this.

Dependabot updates work with this.

See also:
https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash

**Comment by xynydev** [comment]
Does this really require CLI changes? I'd assume that you'd want to make changes in the github action (https://github.com/blue-build/github-action/blob/main/action.yml). Specifying commit hashes for actions we use in our action is probably a good idea.

I'm not sure about using the commit hash for the BlueBuild action in the template, though. If all actions we use in our action are also referenced with commit actions, that probably means a lot more commits. In my experience, Dependabot is often pretty slow with recommending new updates to its users, and more updates to our action means more update PRs to users and more maintenance chores for our users.

I'm not against it either, and everyone is obviously free to do it in their own repos. I'm just not sure if it's a good default.

The security angle is neglible too... If a user doesn't trust BlueBuild to not put something bad in the GitHub Action, can they trust our modules or CLI either? I guess modules could also be hash-versioned, but that's then just another thing that needs maintenance (and is not even handle by Dependabot). That would be possible, though, once CLI implements module versioning support.

**Comment by fiftydinar** [comment]
> Does this really require CLI changes? I'd assume that you'd want to make changes in the github action (https://github.com/blue-build/github-action/blob/main/action.yml).

Yes, that's what I meant, sorry.

> In my experience, Dependabot is often pretty slow with recommending new updates to its users, and more updates to our action means more update PRs to users and more maintenance chores for our users.

Interesting, It usually takes a day at maximum for me for Dependabot to recommend me an update.

> I'm not against it either, and everyone is obviously free to do it in their own repos. I'm just not sure if it's a good default.

From perspective of easiness & intuitiveness, yeah, it's not a good default.

> The security angle is neglible too... If a user doesn't trust BlueBuild to not put something bad in the GitHub Action, can they trust our modules or CLI either?

When you put it this way, I would agree. If some bad actor would take the repo, he would surely find the other way to do the bad things. At that point, this "improvement" is neglible as you said.
