### ISSUE TITLE
is semantic.yml still relevant?

### ISSUE THREAD

**Issue by xynydev** [blue-build/template#7]
I think it requires this GitHub app be manually installed: https://github.com/marketplace/semantic-prs/plan/MLP_kgDNHVc

Besides, a lot of people don't just care about following conventional commits in their custom images.

**Comment by gmpinder** [comment]
Yeah I think that removing it wouldn't hurt, especially to your point that users most likely wouldn't care

**Comment by xynydev** [comment]
Deleted
